### ISSUE TITLE
Identify if the bunyan stream is a splunk stream

### ISSUE THREAD

**Issue by lavishAgrawal** [splunk/splunk-bunyan-logger#10]
I am writing to multiple log streams in the bunyan logger viz. A file stream, stdout and a splunk stream.
I am using these together by pushing them to the streams array.
Is there a way to identify which element of the streams array corresponds to splunk stream, if the order in which they were pushed to the array is unknown?

When I print my streams list, I get the following output:
[ **{ level: 30,
    type: 'raw',
    setEventFormatter: [Function: setEventFormatter],
    on: [Function: on],
    flush: [Function: flush],
    stream: 
     SplunkStream {
       logger: [Object],
       send: [Function],
       _events: [Object],
       _eventsCount: 1 },
    raw: true,
    closeOnExit: false }**,
  { level: 20,
    path: './productDI.log',
    period: '2h',
    count: 3,
    type: 'file',
    raw: false,
    reemitErrorEvents: true,
    stream: 
     WriteStream {
       _writableState: [Object],
       writable: true,
       domain: null,
       _events: [Object],
       _eventsCount: 2,
       _maxListeners: undefined,
       path: './productDI.log',
       fd: null,
       flags: 'a',
       mode: 438,
       start: undefined,
       autoClose: true,
       pos: undefined,
       bytesWritten: 0 },
    closeOnExit: false },
  { level: 20,
    stream: 
     Socket {
       connecting: false,
       _hadError: false,
       _handle: [Object],
       _parent: null,
       _host: null,
       _readableState: [Object],
       readable: false,
       domain: null,
       _events: [Object],
       _eventsCount: 3,
       _maxListeners: undefined,
       _writableState: [Object],
       writable: true,
       allowHalfOpen: false,
       destroyed: false,
       _bytesDispatched: 0,
       _sockname: null,
       _pendingData: null,
       _pendingEncoding: '',
       server: null,
       _server: null,
       _type: 'pipe',
       fd: 1,
       _isStdio: true,
       destroySoon: [Function],
       destroy: [Function] },
    type: 'stream',
    raw: false,
    closeOnExit: false } ]

Out of all the streams attached above, I want to access the one highlighted. For that I first need to figure out which stream correspond to SplunkStream. How do I do that?

**Comment by shakeelmohamed** [comment]
Hi @lavishAgrawal.
When creating the `SplunkStream`, I would do something like the following (since we don't export the `SplunkStream` class):

```js
// assumed modules are required as in examples/basic.js

var splunkStream = splunkBunyan.createStream(config);
var splunkStreamType = typeof splunkStream;

// create Bunyan logger...
// assumed streamList is the name of the variable containing the list of streams you shared above

for (var s in streamList) {
    if (streamList[s] instanceof splunkStreamType) {
        // This is the stream you want
    }
}
```

Feel free to re-open if this strategy doesn't work.
