### ISSUE TITLE
Getting ECONNRESET Error: socket hang up error

### ISSUE THREAD

**Issue by alok2k5ingh** [splunk/splunk-bunyan-logger#32]
Trying to implement the same example as mentioned in the README file but getting the error:
ECONNRESET Error: socket hang up error

Have checkup the token and splunk HEC endpoint, it's working.
Can someone please help

Tried on:
Node version: v14.17.6

"dependencies": {
    "bunyan": "^1.8.15",
    "splunk-bunyan-logger": "^0.11.0"
  }

**Comment by rkistinger-carvana** [comment]
@alok2k5ingh I'm having the same issue. What was your solution?
